/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef HDF_AUDIO_DRIEVR_TEST_H
#define HDF_AUDIO_DRIEVR_TEST_H

#include "hdf_main_test.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif /* __cplusplus */

typedef enum {
    AUDIO_DRIVER_TESTDAIDEVICEINIT,
    AUDIO_DRIVER_TESTDAISTARTUP,
    AUDIO_DRIVER_TESTDAIHWPARAMS,
    AUDIO_DRIVER_TESTDAI_TRIGGER,

    AUDIO_DRIVER_TESTCODECHALSYSINIT,
    AUDIO_DRIVER_TESTACODECREGBITSREAD,
    AUDIO_DRIVER_TESTCODECREGBITSUPDATE,
    AUDIO_DRIVER_TESTCODECREGDEFAULTINIT,
    AUDIO_DRIVER_TESTCODECSETADCTUNEENABLE,
    AUDIO_DRIVER_TESTCODECDAIPARAMSUPDATE,
    AUDIO_DRIVER_TESTAUDIOCODECAIAOSETCTRLOPS,
    AUDIO_DRIVER_TESTAUDIOCODECAIAOGETCTRLOPS,

    AUDIO_DRIVER_TESTCODECDEVICEINIT,
    AUDIO_DRIVER_TESTCODECDAIDEVICEINIT,
    AUDIO_DRIVER_TESTCODECDAIHWPARAMS,
    AUDIO_DRIVER_TESTCODECDAISTARTUP,

    AUDIO_DRIVER_TESTAIOPREGCFG,
    AUDIO_DRIVER_TESTAIAOHALSYSINIT,
    AUDIO_DRIVER_TESTAIAOCLOCKRESET,
    AUDIO_DRIVER_TESTAIAOHALREADREG,
    AUDIO_DRIVER_TESTAOPHALSETBUFFRPTR,
    AUDIO_DRIVER_TESTAOPHALSETBUFFWPTR,
    AUDIO_DRIVER_TESTAIPHALSETBUFFWPTR,
    AUDIO_DRIVER_TESTAIPHALSETBUFFRPTR,
    AUDIO_DRIVER_TESTAOPHALSETTXSTART,
    AUDIO_DRIVER_TESTAIPHALSETRXSTART,
    AUDIO_DRIVER_TESTAOPHALDEVENABLE,
    AUDIO_DRIVER_TESTAIAODEVICEINIT,
    AUDIO_DRIVER_TESTAUDIOAOINIT,
    AUDIO_DRIVER_TESTAUDIOAIINIT,
    AUDIO_DRIVER_TESTAIAOSYSPINMUX,
    AUDIO_DRIVER_TESTAIAOGETMCLK,
    AUDIO_DRIVER_TESTAIAOSETSYSCTLREGVALUE,

    AUDIO_DRIVER_TESTAUDIODMADEVICEINIT,
    AUDIO_DRIVER_TESTHI3516DMABUFALLOC,
    AUDIO_DRIVER_TESTHI3516DMABUFFREE,
    AUDIO_DRIVER_TESTHI3516DMAREQUESTCHANNEL,
    AUDIO_DRIVER_TESTHI3516DMACONFIGCHANNEL,
    AUDIO_DRIVER_TESTHI3516DMAPREP,
    AUDIO_DRIVER_TESTHI3516DMASUBMIT,
    AUDIO_DRIVER_TESTHI3516DMAPENDING,
    AUDIO_DRIVER_TESTHI3516DMAPAUSE,
    AUDIO_DRIVER_TESTHI3516DMARESUME,
    AUDIO_DRIVER_TESTHI3516DMAPOINTER,
} HdfHi3516DV300DirverTestCaseCmd;

int32_t HdfAudioDriverEntry(HdfTestMsg *msg);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif /* HDF_DRIEVR_TEST_H */
