/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef HI3516_AUDIO_DRIVER_TEST_H
#define HI3516_AUDIO_DRIVER_TEST_H

#define G_TEST_HI3516_AUDIO_DRIVER_TYPE 702

typedef enum {
    TESTDAIDEVICEINIT,
    TESTDAISTARTUP,
    TESTDAIHWPARAMS,
    TESTDAITRIGGER,

    TESTCODECHALSYSINIT,
    TESTACODECREGBITSREAD,
    TESTCODECREGBITSUPDATE,
    TESTCODECREGDEFAULTINIT,
    TESTCODECSETADCTUNEENABLE,
    TESTCODECDAIPARAMSUPDATE,
    TESTAUDIOCODECAIAOSETCTRLOPS,

    TESTAUDIOCODECAIAOGETCTRLOPS,
    TESTCODECDEVICEINIT,
    TESTCODECDAIDEVICEINIT,
    TESTCODECDAIHWPARAMS,
    TESTCODECDAISTARTUP,

    TESTAIOPREGCFG,
    TESTAIAOHALSYSINIT,
    TESTAIAOCLOCKRESET,
    TESTAIAOHALREADREG,
    TESTAOPHALSETBUFFRPTR,
    TESTAOPHALSETBUFFWPTR,
    TESTAIPHALSETBUFFWPTR,
    TESTAIPHALSETBUFFRPTR,
    TESTAOPHALSETTXSTART,
    TESTAIPHALSETRXSTART,
    TESTAOPHALDEVENABLE,
    TESTAIAODEVICEINIT,
    TESTAUDIOAOINIT,
    TESTAUDIOAIINIT,
    TESTAIAOSYSPINMUX,
    TESTAIAOGETMCLK,
    TESTAIAOSETSYSCTLREGVALUE,
    TESTAUDIODMADEVICEINIT,
    TESTHI3516DMABUFALLOC,

    TESTHI3516DMABUFFREE,
    TESTHI3516DMAREQUESTCHANNEL,
    TESTHI3516DMACONFIGCHANNEL,
    TESTHI3516DMAPREP,
    TESTHI3516DMASUBMIT,
    TESTHI3516DMAPENDING,
    TESTHI3516DMAPAUSE,
    TESTHI3516DMARESUME,
    TESTHI3516DMAPOINTER,
} HdfHi3516AudioDriverTestCmd;

#endif /* HI3516_AUDIO_DRIVER_TEST_H */
